project:
  type: website
  output-dir: docs

website:
  title: "a11y_ds"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - installation_r_vscode.qmd
      - vscode.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
